### ISSUE TITLE
Gitbot code example needs update

### ISSUE THREAD

**Issue by ivanayov** [openfaas/workshop#90] opened 2018-11-22 13:16 UTC
At this part of Lab5 the code example needs updating/fixing:
https://github.com/openfaas/workshop/blob/master/lab5.md#update-the-issue-bot-function

At the rest of the Lab it's working well.

**Comment by alexellis** [comment] 2019-06-26 14:33
@ivanayov can you clarify what update is needed and if this is still an issue?

**Comment by rgee0** [comment] 2019-10-02 18:51
Closing as the issue is aged and suggested change is unclear.  The workshop has been run multiple times since the issue was opened so this would have either highlighted the issue & consequently been corrected, or failed to exposed the issue.

**Closed by rgee0** 2019-10-02 18:51 UTC
